# Generated by Django 6.0.4 on 2026-06-04 16:52

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('permite_fracionamento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'unidade de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200)),
                ('entidade', models.CharField(max_length=120)),
                ('entidade_id', models.BigIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=30)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_item', models.CharField(choices=[('equipamento', 'Equipamento'), ('consumivel', 'Consumível'), ('reagente', 'Reagente'), ('epi', 'EPI'), ('peca', 'Peça')], max_length=40)),
                ('controlado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='itens', to='inventory.categoria')),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='itens', to='inventory.unidademedida')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=200, unique=True)),
                ('tombamento', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('status_operacional', models.CharField(choices=[('ativo', 'Ativo'), ('em_manutencao', 'Em manutenção'), ('inativo', 'Inativo'), ('descartado', 'Descartado')], default='ativo', max_length=40)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_baixa', models.CharField(choices=[('descarte', 'Descarte'), ('baixa', 'Baixa'), ('perda', 'Perda'), ('obsolescencia', 'Obsolescência'), ('avaria_irrecuperavel', 'Avaria irrecuperável')], max_length=40)),
                ('motivo', models.TextField()),
                ('destino_final', models.TextField(blank=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=120)),
                ('realizada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='baixas', to='inventory.equipamento')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='baixas', to='inventory.item')),
            ],
            options={
                'verbose_name_plural': 'baixas',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('tipo', models.CharField(choices=[('campus', 'Campus'), ('predio', 'Prédio'), ('laboratorio', 'Laboratório'), ('armario', 'Armário'), ('posicao', 'Posição')], max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('localizacao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='inventory.localizacao')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_contada', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('diferenca', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantidade_contada'), '-', models.F('quantidade_sistema')), output_field=models.DecimalField(decimal_places=3, max_digits=14))),
                ('observacao', models.TextField(blank=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.inventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='inventory.item')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('nivel_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('nivel_alerta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='inventory.item')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estoques', to='inventory.localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=120)),
                ('fabricante', models.CharField(blank=True, max_length=160)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.item')),
            ],
            options={
                'ordering': ['data_validade', 'codigo_lote'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('descricao_servico', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em execução'), ('aguardando_pecas', 'Aguardando peças'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='aberta', max_length=40)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('inicio_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('laudo_emitido', models.BooleanField(default=False)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordens_servico', to='inventory.equipamento')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('calibracao', 'Calibração'), ('verificacao', 'Verificação'), ('inspecao', 'Inspeção')], max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('realizada_em', models.DateTimeField(blank=True, null=True)),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proximo_vencimento', models.DateField(blank=True, null=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='inventory.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_solicitante', models.CharField(blank=True, max_length=160)),
                ('finalidade', models.TextField()),
                ('justificativa', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('em_aprovacao', 'Em aprovação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='aberta', max_length=30)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_atendimento', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_aprovada', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantidade_atendida', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requisicoes', to='inventory.item')),
                ('lote_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lote')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.requisicao')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste'), ('baixa', 'Baixa'), ('inventario', 'Inventário')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.baixa')),
                ('inventario_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.inventarioitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes', to='inventory.item')),
                ('localizacao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='inventory.localizacao')),
                ('localizacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='inventory.localizacao')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.ordemservico')),
                ('requisicao_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.requisicaoitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='localizacao',
            constraint=models.UniqueConstraint(fields=('tipo', 'nome', 'localizacao_pai'), name='uniq_localizacao_tipo_nome_pai'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('item', 'localizacao'), name='uniq_estoque_item_localizacao'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('item', 'codigo_lote'), name='uniq_lote_item_codigo'),
        ),
    ]
